### ISSUE TITLE
Ordering of calls.

### ISSUE THREAD

**Issue by joelataylor** [danielmilner/FireTree-Transient-Fallback#1]
Hi Daniel, quick question. 
Should I be setting the transient BEFORE I try to call it? I was assuming that if NEITHER true transient or backup transient existed, it would still call the hook. But it doesn't seem that was your intent?

Looking at https://github.com/danielmilner/FireTree-Transient-Fallback/blob/master/FireTree_Transient_Fallback.php#L68

**Comment by danielmilner** [comment]
You're right. That's a bug. I should have ended the if statement at line 72 and lines 74 and 75 should be outside of the if statement.

**Comment by joelataylor** [comment]
Hmm, that would still leave a `false` response when you really would prefer the action to be triggered immediately to return the real `data`.

Maybe my use-case is a lil' different than yours.

**Comment by danielmilner** [comment]
Lines 78-79 should probably be changed to this:

``` php
$data = get_transient( $fallback_transient );

wp_clear_scheduled_hook( $hook, $args );
wp_schedule_single_event( time(), $hook, $args );

return $data;
```

**Comment by danielmilner** [comment]
Commit d68c0c4
